name: Continous Integration

on:
  push:
    branches: 
      - develop
      - release/*
    tags-ignore:
      - '*'
      
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Setup .NET v5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
    - name: Setup .NET Core v3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          
    - name: Build
      run: dotnet build ./src/ServiceComponents.sln --configuration Release
    
    - name: Test
      run: dotnet test ./src/ServiceComponents.sln